version: "3.9"

services:
  webscraper:
    build: ./webscraper
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    env_file:
      - ./webscraper/.env
    command: /bin/sh -c "while true ; do pipenv run python3 /app/main.py ; sleep 15 ; done"
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8-alpine
    platform: linux/amd64 # Only needed when running on Apple Silicon
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana-oss:9.0.3
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
