version: "3.9"

services:
  webscraper:
    build: ./webscraper
    container_name: webscraper
    environment:
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=ONJtSJuo7VXGjUjV80Xs44GGqxnyQHu
      - INFLUX_ORG=ulrichlehner
      - INFLUX_BUCKET=smartmeter
      - TIMEZONE=Europe/Vienna
    env_file:
      - ./webscraper/.env
    depends_on:
      - influxdb
    restart: always
    networks:
      - local
  influxdb:
    image: influxdb:2.3-alpine
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=e6bWQWSAeIkKOCYDm2WJbuaXLyGhOGO
      - DOCKER_INFLUXDB_INIT_ORG=ulrichlehner
      - DOCKER_INFLUXDB_INIT_BUCKET=smartmeter
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ONJtSJuo7VXGjUjV80Xs44GGqxnyQHu
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    restart: always
    networks:
      - local
  grafana:
    image: grafana/grafana-oss:9.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always
    networks:
      - local

networks:
  local:
