version: '3.9'

services:
  databot:
    # platform: linux/arm64/v8
    # build: ./databot
    image: ghcr.io/ulrichson/homebase:main
    container_name: databot
    environment:
      - INFLUX_URL=http://influxdb:8086
    env_file:
      - ./.env
    depends_on:
      - influxdb
    restart: always
    volumes:
      - ./data/databot:/app/export
    networks:
      - local
  influxdb:
    image: influxdb:2.3-alpine
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
    env_file:
      - ./.env
    ports:
      - '8086:8086'
    volumes:
      - ./data/influxdb:/var/lib/influxdb2
    restart: always
    networks:
      - local

networks:
  local:
