version: "3.9"

services:
  webscraper:
    build: ./webscraper
    container_name: webscraper
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
    env_file:
      - ./webscraper/.env
    depends_on:
      - influxdb
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    platform: linux/amd64 # Only needed when running on Apple Silicon
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana-oss:9.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
